def _handle_init(args) -> int:
    """Post-install bootstrap for a project.

    Provisions:
    1. Verifies profiles (worker, orchestrator)
    1a. Checks profile model config and max_turns
    2. Creates config overlay
    3. Provisions cron scripts to $HERMES_HOME/scripts/
    4. Registers skill bundle for non-plugin Hermes sessions
    5. Sets HERMES_ENABLE_PROJECT_PLUGINS=true
    6. Verifies gateway
    7. Outputs readiness report with cron job commands
    """
    project_root = Path(args.project_root).resolve()
    hermes_home = Path(os.environ.get("HERMES_HOME", Path.home() / ".hermes"))

    print(f"kanban-advanced init -- bootstrapping {project_root}")
    print(f"  HERMES_HOME: {hermes_home}")
    print(f"  Working branch: {args.working_branch}")
    print()

    errors = []

    # 1. Verify profiles exist
    print("1. Checking profiles...")
    try:
        result = subprocess.run(
            [HERMES_BIN, "profile", "list"],
            capture_output=True, text=True, timeout=10
        )
        profiles_output = result.stdout
    except Exception:
        profiles_output = ""

    for profile in ["worker", "orchestrator"]:
        if profile not in profiles_output:
            msg = f"   Profile '{profile}' not found. Create it with: hermes profile create {profile}"
            print(f"   X {msg}")
            errors.append(msg)
        else:
            print(f"   OK {profile}")

    # 1a. Check profile model config
    print()
    print("1a. Checking profile model config...")
    for profile in ["worker", "orchestrator"]:
        try:
            result = subprocess.run(
                [HERMES_BIN, "-p", profile, "config", "get", "model.default"],
                capture_output=True, text=True, timeout=10
            )
            model = result.stdout.strip()
            if model and model != "None":
                print(f"   OK {profile}: model.default = {model}")
            else:
                print(f"   !  {profile}: no model configured")
                print(f"      Fix: hermes -p {profile} config set model.default <model-name>")
                print(f"           hermes -p {profile} config set model.provider <provider-name>")
                if profile == "orchestrator":
                    print(f"           hermes -p {profile} config set model.base_url <url>  # if needed")
        except Exception:
            pass

    # 1b. Check orchestrator max_turns
    print()
    print("1b. Checking orchestrator max_turns...")
    try:
        result = subprocess.run(
            [HERMES_BIN, "-p", "orchestrator", "config", "get", "model.max_turns"],
            capture_output=True, text=True, timeout=10
        )
        max_turns = result.stdout.strip()
        if max_turns and max_turns.isdigit() and int(max_turns) >= 180:
            print(f"   OK orchestrator: max_turns = {max_turns}")
        else:
            current = max_turns if max_turns else "default (90)"
            print(f"   !  orchestrator: max_turns = {current} -- recommend 180 for complex plans")
            print(f"      Fix: hermes -p orchestrator config set model.max_turns 180")
    except Exception:
        pass

    # 2. Create config overlay
    print()
    print("2. Creating config overlay...")
    overlay_dir = project_root / ".hermes" / "kanban-overrides"
    overlay_dir.mkdir(parents=True, exist_ok=True)
    config_file = overlay_dir / "kanban-config.yaml"
    config_file.write_text(f"""# kanban-advanced config overlay -- generated by kanban-advanced init
working_branch: {args.working_branch}
bundle_path: {PLUGIN_ROOT}
skills_output_path: {hermes_home / 'skills' / 'devops'}
profiles:
  orchestrator: orchestrator
  worker: worker
""")
    print(f"   OK {config_file}")

    # 3. Provision cron scripts
    print("3. Provisioning cron scripts...")
    cron_dir = hermes_home / "scripts"
    cron_dir.mkdir(parents=True, exist_ok=True)

    for script_name in ["auto_unblock.sh", "board_keeper.sh"]:
        src = SCRIPTS_DIR / script_name
        dst = cron_dir / script_name
        if src.exists():
            dst.write_text(src.read_text())
            dst.chmod(0o755)
            print(f"   OK {script_name} -> {dst}")
        else:
            msg = f"   X {script_name} not found at {src}"
            print(msg)
            errors.append(msg)

    # 4. Register skill bundle (for non-plugin Hermes sessions)
    print("4. Registering skill bundle...")
    bundle_src = PLUGIN_ROOT / "bundles" / "kanban-advanced.yaml"
    bundle_dir = hermes_home / "skill-bundles"
    bundle_dst = bundle_dir / "kanban-advanced.yaml"

    if bundle_src.exists():
        bundle_dir.mkdir(parents=True, exist_ok=True)
        bundle_dst.write_text(bundle_src.read_text())
        print(f"   OK kanban-advanced.yaml -> {bundle_dst}")

        try:
            subprocess.run(
                [HERMES_BIN, "bundles", "reload"],
                capture_output=True, text=True, timeout=10
            )
            print("   OK bundles reloaded")
        except Exception:
            print("   X Could not reload bundles (hermes may not be running)")
    else:
        msg = f"   X Bundle not found at {bundle_src}"
        print(msg)
        errors.append(msg)

    # 5. Set HERMES_ENABLE_PROJECT_PLUGINS
    print("5. Setting HERMES_ENABLE_PROJECT_PLUGINS=true...")
    env_file = project_root / ".env"
    env_line = "HERMES_ENABLE_PROJECT_PLUGINS=true\n"

    if env_file.exists():
        content = env_file.read_text()
        if "HERMES_ENABLE_PROJECT_PLUGINS" not in content:
            env_file.write_text(content + env_line)
            print("   OK Added to .env")
        else:
            print("   OK Already set in .env")
    else:
        env_file.write_text(env_line + "\n")
        print("   OK Created .env with setting")

    # 6. Verify gateway
    print("6. Checking gateway...")
    try:
        result = subprocess.run(
            [HERMES_BIN, "gateway", "status"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            print(f"   OK Gateway running")
        else:
            msg = "Gateway not running -- start with 'hermes gateway start'"
            print(f"   X {msg}")
            errors.append(msg)
    except Exception as exc:
        msg = f"Could not check gateway: {exc}"
        print(f"   X {msg}")
        errors.append(msg)

    # 7. Readiness report
    print()
    print("=" * 50)
    if errors:
        print("WARNING Bootstrap complete with warnings:")
        for e in errors:
            print(f"  - {e}")
        return 1
    else:
        print("OK kanban-advanced is ready!")
        print(f"  Config: {config_file}")
        print(f"  Cron scripts: {cron_dir}")
        print(f"  Skill bundle: {bundle_dst}")
        print(f"  Profiles: worker, orchestrator")
        print()
        print("  Next steps:")
        print(f"    1. Configure profile models if not set (see check 1a above)")
        print(f"    2. Set up cron jobs for autonomous operation:")
        print(f"       hermes cronjob create --schedule \"every 1m\" --script \"auto_unblock.sh\" --no-agent --name kanban-auto-unblock")
        print(f"       hermes cronjob create --schedule \"every 3m\" --script \"board_keeper.sh\" --no-agent --name kanban-board-keeper")
        print(f"    3. Start gateway: hermes gateway start")
        print(f"    4. Decompose a plan: hermes kanban-advanced decompose --plan <file>")
        return 0