#!/usr/bin/env bash
# kanban-advanced-init.sh — Post-install bootstrap for kanban-advanced plugin.
#
# Run this after `hermes plugins install thebizfixer/hermes-kanban-advanced-workflow`
# to provision per-project configuration, cron scripts, and profiles.
#
# Usage:
#   bash kanban-advanced-init.sh [--project-root .] [--working-branch <branch-name>]
#
# This is a convenience wrapper. The same functionality is available via:
#   hermes kanban-advanced init --project-root . --working-branch <branch-name>

set -euo pipefail

PROJECT_ROOT="${1:-.}"
WORKING_BRANCH="${2:-main}"
HERMES_HOME="${HERMES_HOME:-$HOME/.hermes}"
PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "kanban-advanced init"
echo "  Project root:   $PROJECT_ROOT"
echo "  Working branch: $WORKING_BRANCH"
echo "  HERMES_HOME:    $HERMES_HOME"
echo "  Plugin dir:     $PLUGIN_DIR"
echo ""

# ── 1. Verify hermes is available ───────────────────────────────────
if ! command -v hermes &>/dev/null; then
    echo "ERROR: hermes not found on PATH. Install Hermes Agent first."
    exit 1
fi

# ── 2. Check profiles ───────────────────────────────────────────────
echo "1. Checking profiles..."
MISSING=()
for p in worker orchestrator; do
    if hermes profile list 2>/dev/null | grep -q "$p"; then
        echo "   ✓ $p"
    else
        echo "   ⚠ $p not found — create with: hermes profile create $p"
        MISSING+=("$p")
    fi
done

if [ ${#MISSING[@]} -gt 0 ]; then
    echo ""
    echo "Missing profiles: ${MISSING[*]}"
    echo "Create them before running kanban workflows:"
    for p in "${MISSING[@]}"; do
        echo "  hermes profile create $p"
    done
fi

# ── 3. Create config overlay ────────────────────────────────────────
echo ""
echo "2. Creating config overlay..."
OVERLAY_DIR="$PROJECT_ROOT/.hermes/kanban-overrides"
mkdir -p "$OVERLAY_DIR"

cat > "$OVERLAY_DIR/kanban-config.yaml" <<EOF
# kanban-advanced config overlay — generated by kanban-advanced-init.sh
working_branch: $WORKING_BRANCH
bundle_path: $PLUGIN_DIR
skills_output_path: $HERMES_HOME/skills/devops
profiles:
  orchestrator: orchestrator
  worker: worker
EOF
echo "   ✓ $OVERLAY_DIR/kanban-config.yaml"

# ── 4. Provision cron scripts ───────────────────────────────────────
echo ""
echo "3. Provisioning cron scripts..."
CRON_DIR="$HERMES_HOME/scripts"
mkdir -p "$CRON_DIR"

for script in auto_unblock.sh board_keeper.sh; do
    src="$PLUGIN_DIR/scripts/$script"
    dst="$CRON_DIR/$script"
    if [ -f "$src" ]; then
        cp "$src" "$dst"
        chmod +x "$dst"
        echo "   ✓ $script → $dst"
    else
        echo "   ⚠ $script not found at $src"
    fi
done

# ── 4. Register skill bundle ────────────────────────────────────────
echo ""
echo "4. Registering skill bundle..."
BUNDLE_SRC="$PLUGIN_DIR/bundles/kanban-advanced.yaml"
BUNDLE_DIR="$HERMES_HOME/skill-bundles"
BUNDLE_DST="$BUNDLE_DIR/kanban-advanced.yaml"

if [ -f "$BUNDLE_SRC" ]; then
    mkdir -p "$BUNDLE_DIR"
    cp "$BUNDLE_SRC" "$BUNDLE_DST"
    echo "   ✓ kanban-advanced.yaml → $BUNDLE_DST"
    hermes bundles reload 2>/dev/null && echo "   ✓ bundles reloaded" || echo "   ⚠ Could not reload bundles (hermes may not be running)"
else
    echo "   ⚠ Bundle not found at $BUNDLE_SRC"
fi

# ── 5. Set HERMES_ENABLE_PROJECT_PLUGINS ────────────────────────────
echo ""
echo "5. Setting HERMES_ENABLE_PROJECT_PLUGINS=true..."
ENV_FILE="$PROJECT_ROOT/.env"
if ! grep -q "HERMES_ENABLE_PROJECT_PLUGINS" "$ENV_FILE" 2>/dev/null; then
    echo "HERMES_ENABLE_PROJECT_PLUGINS=true" >> "$ENV_FILE"
    echo "   ✓ Added to $ENV_FILE"
else
    echo "   ✓ Already set in $ENV_FILE"
fi

# ── 6. Gateway check ─────────────────────────────────────────────────
echo ""
echo "6. Checking gateway..."
if hermes gateway status &>/dev/null; then
    echo "   ✓ Gateway running"
else
    echo "   ⚠ Gateway not running — start with: hermes gateway start"
fi

# ── 7. Readiness report ─────────────────────────────────────────────
echo ""
echo "=========================================="
echo "kanban-advanced init complete."
echo ""
echo "Next steps:"
echo "  1. Start gateway:  hermes gateway start"
echo "  2. Create cron jobs (see README for cron commands)"
echo "  3. Decompose a plan: hermes kanban-advanced decompose --plan <file>"
echo "=========================================="
